fix ofox

diff --git a/.github/workflows/ofox.yml b/.github/workflows/ofox.yml
--- a/.github/workflows/ofox.yml
+++ b/.github/workflows/ofox.yml
@@ -1,4 +1,4 @@
-name: OrangeFox Recovery Builder
+name: OrangeFox [OFRP]
 
 on:
   workflow_dispatch:
@@ -9,43 +9,43 @@ on:
         default: '12.1'
         type: choice
         options:
-        - '12.1'
-        - '11.0'
-        - '10.0'
+        - 12.1
+        - 11.0
+        - 10.0
+        - 9.0
+        - 8.1
+        - 7.1
+        - 6.0
       DEVICE_TREE:
-        description: 'Device Tree URL'
+        description: 'Custom Recovery Tree'
         required: true
         default: 'https://github.com/QOS3/android_device_samsung_gta4lve'
       DEVICE_TREE_BRANCH:
-        description: 'Device Tree Branch'
+        description: 'Custom Recovery Tree Branch'
         required: true
         default: 'android-12.1'
-      DEVICE_PATH:
-        description: 'Device Path (relative to source root)'
-        required: true
-        default: 'device/samsung/gta4lve'
-      DEVICE_NAME:
-        description: 'Device Codename'
-        required: true
-        default: 'gta4lve'
       BUILD_TARGET:
-        description: 'Build Target'
+        description: 'Specify your Build Target'
         required: true
         default: 'recovery'
         type: choice
         options:
-        - recovery
         - boot
+        - recovery
         - vendorboot
-      RECOVERY_TAR:
-        description: 'Create recovery.tar'
+      LDCHECK:
+        description: 'Use LDCHECK'
         required: false
-        default: true
+        default: 'false'
         type: boolean
+      LDCHECKPATH:
+        description: 'Path of blobs to check'
+        required: true
+        default: 'system/bin/qseecomd'
 
 jobs:
   build:
-    name: Build OrangeFox by ${{ github.actor }}
+    name: Build OFRP by ${{ github.actor }}
     runs-on: ubuntu-22.04
     if: github.event.repository.owner.id == github.event.sender.id
     env:
@@ -53,131 +53,172 @@ jobs:
     permissions:
       contents: write
     steps:
-    - name: Check Out
+    - name: Checkout
       uses: actions/checkout@v4
 
     - name: Display Inputs
       run: |
-        echo "Manifest Branch : ${{ inputs.MANIFEST_BRANCH }}"
-        echo "Device Tree     : ${{ inputs.DEVICE_TREE }}"
-        echo "Device Branch   : ${{ inputs.DEVICE_TREE_BRANCH }}"
-        echo "Build Target    : ${{ inputs.BUILD_TARGET }}image"
+        echo "Manifest Branch: ${{ inputs.MANIFEST_BRANCH }}"
+        echo "Device Tree: ${{ inputs.DEVICE_TREE }}"
+        echo "Device Branch: ${{ inputs.DEVICE_TREE_BRANCH }}"
+        echo "Build Target: ${{ inputs.BUILD_TARGET }}image"
 
-    - name: Cleanup
+    - name: Clean-up
       uses: rokibhasansagar/slimhub_actions@main
 
-    - name: Set Swap Space
+    - name: Swap Space
       uses: pierotofy/set-swap-space@master
       with:
         swap-size-gb: 12
 
-    - name: Prepare the environment
+    - name: Build Environment
       run: |
-        sudo apt update
-        sudo apt -y upgrade
-        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
-          libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev \
-          libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev \
-          liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop \
-          pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp \
-          qemu-user-static libstdc++-10-dev libtinfo5 libgflags-dev libncurses5 python3
+        sudo apt install aria2 -y
+        git clone https://gitlab.com/OrangeFox/misc/scripts
+        cd scripts
+        sudo bash setup/android_build_env.sh
 
-    - name: Install OpenJDK
-      uses: actions/setup-java@v4
-      with:
-        distribution: 'zulu'
-        java-version: '11'
-
-    - name: Install Git-Repo
+    - name: Set-up Manifest
       run: |
-        mkdir ~/bin
-        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
-        chmod a+x ~/bin/repo
-        sudo ln -sf ~/bin/repo /usr/bin/repo
-
-    - name: Initialize OrangeFox Repo
-      run: |
-        mkdir android-recovery
-        cd android-recovery
+        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
+        cd ${GITHUB_WORKSPACE}/OrangeFox
         git config --global user.name "QOS3"
         git config --global user.email "seefpro11@gmail.com"
-        SYNC_BRANCH="${{ inputs.MANIFEST_BRANCH }}"
-        SYNC_BRANCH="${SYNC_BRANCH#fox_}"
-        repo init --depth=1 \
-          -u https://gitlab.com/OrangeFox/sync.git \
-          -b ${SYNC_BRANCH}
+        git clone https://gitlab.com/OrangeFox/sync.git
+        if [ ${{ inputs.MANIFEST_BRANCH }} == '11.0' ] || [ ${{ inputs.MANIFEST_BRANCH }} == '12.1' ]; then
+            echo "CHECK_LEGACY_BRANCH=false" >> $GITHUB_ENV
+            cd sync
+            ./orangefox_sync.sh --branch ${{ inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
+        else
+            echo "CHECK_LEGACY_BRANCH=true" >> $GITHUB_ENV
+            cd sync/legacy
+            ./orangefox_sync_legacy.sh --branch ${{ inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
+        fi
 
-    - name: Repo Sync
+    - name: Replace bootable/recovery with Sprd-patched fork
       run: |
-        cd android-recovery
-        repo sync -j$(nproc --all) --force-sync
-
-    - name: Replace Recovery with Sprd-patched fork
-      run: |
-        cd android-recovery
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
         rm -rf bootable/recovery
-        git clone https://gitlab.com/qos31/Recovery -b fox_12.1 bootable/recovery
+        git clone https://gitlab.com/qos31/Recovery \
+          -b fox_${{ inputs.MANIFEST_BRANCH }} \
+          bootable/recovery --depth=1
 
     - name: Clone Device Tree
       run: |
-        cd android-recovery
-        git clone ${{ inputs.DEVICE_TREE }} \
-          -b ${{ inputs.DEVICE_TREE_BRANCH }} \
-          ./${{ inputs.DEVICE_PATH }}
-        cd ${{ inputs.DEVICE_PATH }}
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
+        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./device_tree
+        cd device_tree
         echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
 
-    - name: Check Build Makefile
+    - name: Extracting variables from .mk file
       run: |
-        cd android-recovery/${{ inputs.DEVICE_PATH }}
-        if [ -f "twrp_${{ inputs.DEVICE_NAME }}.mk" ]; then
-            echo "DEVICE_MAKEFILE=twrp_${{ inputs.DEVICE_NAME }}" >> $GITHUB_ENV
-        elif [ -f "omni_${{ inputs.DEVICE_NAME }}.mk" ]; then
-            echo "DEVICE_MAKEFILE=omni_${{ inputs.DEVICE_NAME }}" >> $GITHUB_ENV
-        else
-            echo "No recovery makefile found!" && exit 1
-        fi
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/device_tree
+        DEVICE_MAKEFILE=""
+        DEVICE_DIRECTORY=""
+        DEVICE_NAME=""
+        for file in *.mk; do
+            makefile=$(sed -n 's/^[[:space:]]*PRODUCT_NAME[[:space:]]*:=\s*\(.*\)/\1/p' "$file")
+            brand=$(sed -n 's/^[[:space:]]*PRODUCT_BRAND[[:space:]]*:=\s*\(.*\)/\1/p' "$file")
+            codename=$(sed -n 's/^[[:space:]]*PRODUCT_DEVICE[[:space:]]*:=\s*\(.*\)/\1/p' "$file")
+            if [[ -n "$makefile" && -n "$brand" && -n "$codename" ]]; then
+                DEVICE_MAKEFILE="$makefile"
+                DEVICE_DIRECTORY="device/$brand"
+                DEVICE_NAME="$codename"
+                echo "DEVICE_MAKEFILE=${DEVICE_MAKEFILE}" >> $GITHUB_ENV
+                echo "DEVICE_NAME=${DEVICE_NAME}" >> $GITHUB_ENV
+                echo "DEVICE_DIRECTORY=${DEVICE_DIRECTORY}" >> $GITHUB_ENV
+                break
+            fi
+        done
+        cd ../
+        mkdir -p "$DEVICE_DIRECTORY"
+        mv device_tree "$DEVICE_DIRECTORY"/"$DEVICE_NAME"
+
+    - name: Installing python2 for legacy builds
+      if: env.CHECK_LEGACY_BRANCH == 'true'
+      run: |
+        sudo apt-get install python2 python-is-python2
 
     - name: Building OrangeFox
       run: |
-        cd android-recovery
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
+        set +e
         source build/envsetup.sh
         export ALLOW_MISSING_DEPENDENCIES=true
-        export FOX_BUILD_DEVICE=${{ inputs.DEVICE_NAME }}
-        export LC_ALL="C"
-        lunch ${{ env.DEVICE_MAKEFILE }}-eng && make clean && mka ${{ inputs.BUILD_TARGET }}image -j$(nproc --all)
-        echo "Done building ${{ inputs.BUILD_TARGET }}.img"
+        set -e
+        if [ ${{ inputs.MANIFEST_BRANCH }} == '11.0' ] || [ ${{ inputs.MANIFEST_BRANCH }} == '12.1' ]; then
+            lunch twrp_${{ env.DEVICE_NAME }}-eng && make clean && mka adbd ${{ inputs.BUILD_TARGET }}image
+        else
+            lunch omni_${{ env.DEVICE_NAME }}-eng && make clean && mka ${{ inputs.BUILD_TARGET }}image
+        fi
 
     - name: Set Build Date
       run: |
         echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
 
-    - name: Create recovery.tar
-      if: inputs.RECOVERY_TAR == true
+    - name: Check if Recovery Exists
       run: |
-        cd android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}
-        if [ -f "${{ inputs.BUILD_TARGET }}.img" ]; then
-          tar -cvf ${{ inputs.BUILD_TARGET }}.tar ${{ inputs.BUILD_TARGET }}.img
-          echo "Recovery TAR created"
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
+        if [ -f out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img ]; then
+            echo "CHECK_IMG_IS_OK=true" >> $GITHUB_ENV
+            echo "MD5_IMG=$(md5sum out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
+        else
+            echo "Recovery img not found."
         fi
-      continue-on-error: true
+        if [ -f out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.zip ]; then
+            echo "CHECK_ZIP_IS_OK=true" >> $GITHUB_ENV
+            echo "MD5_ZIP=$(md5sum out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.zip | cut -d ' ' -f 1)" >> $GITHUB_ENV
+        else
+            echo "Recovery zip not found."
+        fi
 
     - name: Upload to Release
-      uses: softprops/action-gh-release@master
+      if: env.CHECK_IMG_IS_OK == 'true' && env.CHECK_ZIP_IS_OK == 'true'
+      timeout-minutes: 30
+      uses: softprops/action-gh-release@v2
       with:
         files: |
-          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/${{ inputs.BUILD_TARGET }}.img
-          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/${{ inputs.BUILD_TARGET }}.tar
-          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.zip
-        name: OrangeFox for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
-        tag_name: ofox-${{ inputs.DEVICE_NAME }}-${{ env.BUILD_DATE }}-${{ github.run_id }}
+          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img
+          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img.tar
+          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.zip
+          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/ramdisk-recovery.*
+        name: Unofficial OrangeFox for ${{ env.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
+        tag_name: ${{ github.run_id }}
+        fail_on_unmatched_files: false
         body: |
-          ## OrangeFox Recovery
-          - **Branch:** ${{ inputs.MANIFEST_BRANCH }}
-          - **Device:** [Tree](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
-          - **Commit:** [Latest](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }})
-          - **Built by:** @${{ github.actor }}
+          Build: ${{ inputs.MANIFEST_BRANCH }}
+          Device: [Device Tree/Branch](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
+          Commit: Most recent [commit](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
+          MD5 (img): ${{ env.MD5_IMG }}
+          MD5 (zip): ${{ env.MD5_ZIP }}
 
-          ## Flash Instructions
-          - Samsung: flash `.tar` via Odin
-          - Generic: flash `.img` via `fastboot flash recovery`
+    - name: Retry Upload if Failed
+      if: env.CHECK_IMG_IS_OK == 'true' && env.CHECK_ZIP_IS_OK == 'true' && failure()
+      timeout-minutes: 30
+      uses: softprops/action-gh-release@v2
+      with:
+        files: |
+          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img
+          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img.tar
+          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.zip
+          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/ramdisk-recovery.*
+        name: Unofficial OrangeFox for ${{ env.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
+        tag_name: ${{ github.run_id }}
+        fail_on_unmatched_files: false
+        body: |
+          Build: ${{ inputs.MANIFEST_BRANCH }}
+          Device: [Device Tree/Branch](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
+          Commit: Most recent [commit](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
+          MD5 (img): ${{ env.MD5_IMG }}
+          MD5 (zip): ${{ env.MD5_ZIP }}
+
+    - name: Run LDCheck
+      if: inputs.LDCHECK == 'true'
+      run: |
+        cd tools
+        mv -n libneeds ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/recovery/root/
+        mv -n ldcheck ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/recovery/root/
+        cd ../OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/recovery/root
+        python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ inputs.LDCHECKPATH }}
+        echo "Done checking missing dependencies. Review, and reconfigure your tree."
+      continue-on-error: true
